repos:
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint
      args: ['--rcfile=pyproject.toml', --disable=redefined-builtin]
      language: system
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: 'mypy'
        additional_dependencies:
          - 'pydantic'
          - 'types-requests'
